### ISSUE TITLE
Handle null body on 204 no content response

### ISSUE THREAD

**Issue by chiara-jm** [JakeWharton/retrofit2-kotlin-coroutines-adapter#29] opened 2018-10-05 13:19 UTC
Based on

https://github.com/square/retrofit/blob/eb441ed140a124a9f152f82ad05993d502848d9a/retrofit/src/main/java/retrofit2/OkHttpCall.java#L218

this will fail with a NPE: 

https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/5c51f4b1021906c108c7a13099d13203be2bd6f6/src/main/java/com/jakewharton/retrofit2/adapter/kotlin/coroutines/CoroutineCallAdapterFactory.kt#L102

@JakeWharton

**Comment by JakeWharton** [comment] 2018-10-05 13:52
Dupe of #5. This case isn't supported yet.

**Closed as completed by JakeWharton** 2018-10-05 13:52 UTC
